### ISSUE TITLE
Pip install failed.

### ISSUE THREAD

**Issue by nathanoy** [OpenDriveLab/Openpilot-Deepdive#28]
The pip install failed, because the python dev kit was not installed on my system. Perhaps one could mention in the readme that the python dev kit is required, so the next person might not have the same problem:

The install of python dev kit for Ubuntu eg:
```bash
sudo apt-get install python3-dev
```
from this [Stackoverflow answer](https://stackoverflow.com/a/21530768).

The error message is not clear about why it fails, an intensive google search is needed to fix the error.

**Comment by ElectronicElephant** [comment]
Thanks for the information. `python3-dev` is indeed required by [nuscenes-devkit](https://github.com/nutonomy/nuscenes-devkit/blob/master/docs/installation.md).
