### ISSUE TITLE
数据集如何设置

### ISSUE THREAD

**Issue by zhangzhongzhong1** [OpenDriveLab/Openpilot-Deepdive#30]
├── nuscenes  -> soft link to the nusSenes-all dataset
      ├── comma2k19 -> soft link to the Comma2k19 dataset

**Comment by ElectronicElephant** [comment]
Hi, if you do not know how to set up a soft link properly, it's okay to simply copy and paste it into `./comma2k19`.

你好，如果出于一些缘故，无法使用软链接，那么直接将数据集复制粘贴到指定路径也是可以的。

**Comment by zhangzhongzhong1** [comment]
请问一下这两个数据集你这边百度网盘里面有吗？去官网下载好慢

**Comment by ElectronicElephant** [comment]
没有噢~😂

**Comment by zhangzhongzhong1** [comment]
好的，这个数据集太大了，感觉自己的电脑搞不起来
