### ISSUE TITLE
模型训练问题

### ISSUE THREAD

**Issue by Yutong-gannis** [OpenDriveLab/Openpilot-Deepdive#33]
模型的输出始终是一条直线，可能是样本失衡的问题，请问你们有没有遇到这样的问题，用的什么解决方法

**Comment by ElectronicElephant** [comment]
你好，我们没有遇到这样的问题。在 comma2k19 上的结果是比较正常的。如果你更换了自己的数据集，请先检查一下数据集的分布情况

**Comment by xiaowenhe** [comment]
@ElectronicElephant ， 你好，我在comma2k19上训练，也是5个预测路径中，scode最大的结果是一条直线，不能学到曲线信息，有什么改进措施吗？

**Comment by xiaowenhe** [comment]
@ElectronicElephant ，loss正常，大概下降到5左右。能提供log和训练好的模型吗？谢谢！

**Comment by Yutong-gannis** [comment]
@xiaowenhe 我使用sgd优化器，并且只输出一条轨迹后，结果基本就不是一条直线了

**Comment by xiaowenhe** [comment]
@Yutong-gannis ，好的，我也试下，是在训练的时候就M=1吧？

**Comment by ElectronicElephant** [comment]
@Yutong-gannis @xiaowenhe  二位好，我已经从团队离职了很长时间了，具体细节有些记不清楚了。当时训练集群上的日志和权重也因为数据合规的要求，未能拷贝出来。

不过我可以肯定的是，使用 SGD 优化器，网络输出的轨迹会显得更加“平滑”，并且 lr 可以适当调大一些，需要比较多的 epoch 数方能收敛。使用 Adam 优化器的话，在前20epoch的训练过程中，网络输出的轨迹会呈现锯齿状，lr 要适当小一些。最终训练满 100 个 epoch ，两个优化器达到的效果是差不多的。

**Comment by xiaowenhe** [comment]
> @Yutong-gannis @xiaowenhe 二位好，我已经从团队离职了很长时间了，具体细节有些记不清楚了。当时训练集群上的日志和权重也因为数据合规的要求，未能拷贝出来。
> 
> 不过我可以肯定的是，使用 SGD 优化器，网络输出的轨迹会显得更加“平滑”，并且 lr 可以适当调大一些，需要比较多的 epoch 数方能收敛。使用 Adam 优化器的话，在前20epoch的训练过程中，网络输出的轨迹会呈现锯齿状，lr 要适当小一些。最终训练满 100 个 epoch ，两个优化器达到的效果是差不多的。

好的，谢谢！

**Comment by xiaowenhe** [comment]
> @Yutong-gannis @xiaowenhe 二位好，我已经从团队离职了很长时间了，具体细节有些记不清楚了。当时训练集群上的日志和权重也因为数据合规的要求，未能拷贝出来。
> 
> 不过我可以肯定的是，使用 SGD 优化器，网络输出的轨迹会显得更加“平滑”，并且 lr 可以适当调大一些，需要比较多的 epoch 数方能收敛。使用 Adam 优化器的话，在前20epoch的训练过程中，网络输出的轨迹会呈现锯齿状，lr 要适当小一些。最终训练满 100 个 epoch ，两个优化器达到的效果是差不多的。

你好，请问你们在对reg_loss有做其他特殊处理吗？我理解目前只能学习到直线，可能和reg_loss_x, reg_loss_y有关系，因为x的范围可能为[0-200], y的范围大部分都应该在[-10,10]这样子，这样reg_loss_x就会很大，导致只能学习到x信息，也就是只能学习到直线。

**Comment by ElectronicElephant** [comment]
@xiaowenhe 你好，没有做其他特殊处理，只是在激活函数部分，x 用了 exp 而 y 用了 sinh 。这一点在代码中有体现。

**Comment by xiaowenhe** [comment]
> @xiaowenhe 你好，没有做其他特殊处理，只是在激活函数部分，x 用了 exp 而 y 用了 sinh 。这一点在代码中有体现。

好的，谢谢！
