### ISSUE TITLE
Training without convergence on Nuscenes dataset

### ISSUE THREAD

**Issue by Yzichen** [OpenDriveLab/Openpilot-Deepdive#34]
I use SequencePlanningDataset and set num_pts=10, but the training does not converge, how can I reproduce it?

**Comment by ElectronicElephant** [comment]
Hi Zichen,

What do you mean by “does not converge”? Are the loss functions descending normally?

**Comment by Yzichen** [comment]
Not normal.  Should I be using PlanningDataset instead of SequencePlanningDataset.

**Comment by ElectronicElephant** [comment]
You may try commit `b97f9d7`, which supports nuScenes better. Later development moves onto comma2k19 so it might be buggy. Sorry for that.
